# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae2fbb93671f21f2c9a2ec17e68a1a5b59b68d8a60c1d99de7d5a2d41c45af6b5a968e1bc0acfecbb48904fd3f65f02fba96aaa4f38505b5bd0e623f4104d0f4

test:
  secret_key_base: 7d3567198d4a00032f66f92c4172b88cc7ceb1810b6e238077d0fc3e04b77171fa5ef9494327772ba95b2407399c20b15a983ef29d47b0da6ddbb0f11a91478b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
